name: App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Get SSH Key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh $SSH_USER@$SSH_HOST "cd $SSH_PATH && git pull origin main" && npm install && npm run build
      - name: Clean up
        run: |
          rm -rf ~/.ssh
